- name: Issue Labeler
  uses: Naturalclar/issue-action@v1.0.0

name: "Set Issue Label"
on:
  issues:
    types: [opened]

jobs:
  bug:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["bug"]'
          labels: '["bug"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  enhancement:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["enhancement"]'
          labels: '["enhancement"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"